Enable useNativeDriver to improve performance
atlanteh/react-native-slot-machine pull request #7
Opened 2018-06-27 11:46 UTC by weswes

Issue related: https://github.com/atlanteh/react-native-slot-machine/issues/5

Changed top layout animation to translateY and added useNativeDriver.
Default to true as it's way better.

2018-06-27 15:30 UTC, atlanteh commented
Thx for the PR! Can you please change the default useNativeDriver prop (and docs) to false, as to not break compatibility?

2018-06-27 15:35 UTC, atlanteh requested changes
Please fix the above and we can merge it :)
Thx!

2018-06-27 15:35 UTC, atlanteh commented on index.js
> +	    useNativeDriver: true,
Please change to false, and align it to other columns

2018-06-27 15:35 UTC, atlanteh commented on README.md
> +|__`useNativeDriver`__|_Boolean_|Optional|`true`|Enable use of NativeDriver on Animation. See https://facebook.github.io/react-native/docs/animations.html#using-the-native-driver
Please change default to false

2018-06-27 15:35 UTC, atlanteh commented on index.js
> +                return Animated.timing(this.state.values[i], {toValue: animationValue, duration, easing, useNativeDriver: this.props.useNativeDriver});
take it from newProps, not this.props. Also, you can declare useNativeDriver on line 104, and just use it here.

2018-06-27 15:35 UTC, atlanteh commented on index.js
> +            return Animated.timing(value, {toValue: 0, duration: animationDuration, easing, useNativeDriver: this.props.useNativeDriver});
declare variable in line 190 and use here.

2018-06-29 10:59 UTC, weswes commented
Done. 
I hesitated to put default to false as it's fully backward compatible and it's better with true but you decide ;)

2018-07-05 03:51 UTC, atlanteh approved these changes

2018-07-05 03:55 UTC, merged